import {
  Award,
  Bell,
  CalendarCheck,
  CheckCircle2,
  Flag,
  Heart,
  Hourglass,
  Megaphone,
  MessageCircle,
  Reply,
  ShieldAlert,
  Star,
  Swords,
  Trophy,
  UserPlus,
  Users,
  XCircle,
} from 'lucide-react'

export const categoryMeta = {
  match: { icon: Swords, cls: 'text-sky-600 bg-sky-50' },
  booking: { icon: CalendarCheck, cls: 'text-emerald-600 bg-emerald-50' },
  tournament: { icon: Trophy, cls: 'text-amber-600 bg-amber-50' },
  recruitment: { icon: UserPlus, cls: 'text-violet-600 bg-violet-50' },
  team: { icon: Users, cls: 'text-green-600 bg-green-50' },
  social: { icon: Heart, cls: 'text-rose-600 bg-rose-50' },
  system: { icon: Bell, cls: 'text-slate-500 bg-slate-100' },
}

const typeIcons = {
  challenge_received: Swords,
  challenge_accepted: CheckCircle2,
  challenge_declined: XCircle,
  match_accepted: CalendarCheck,
  match_invitation: CalendarCheck,
  match_started: Swords,
  match_finished: Trophy,
  goal_scored: Trophy,
  live_match_started: Trophy,
  score_submitted: Trophy,
  score_confirmed: CheckCircle2,
  score_disputed: Flag,
  new_booking_request: Hourglass,
  booking_confirmation: CheckCircle2,
  booking_cancellation: XCircle,
  booking_rejected: XCircle,
  booking_completed: CalendarCheck,
  reservation_approved: CheckCircle2,
  reservation_rejected: XCircle,
  cancellation_requested: Hourglass,
  cancellation_approved: CheckCircle2,
  cancellation_rejected: XCircle,
  player_application_received: UserPlus,
  player_application_accepted: CheckCircle2,
  player_application_declined: XCircle,
  player_invite_received: UserPlus,
  player_invite_accepted: CheckCircle2,
  team_formation_request: Users,
  announcement: Megaphone,
  new_follower: UserPlus,
  new_comment: MessageCircle,
  comment_reply: Reply,
  like: Heart,
  player_review: Star,
  stadium_review: Star,
  player_awarded_mvp: Award,
  report: ShieldAlert,
  system: Bell,
}

const typeColors = {
  challenge_received: 'text-sky-600 bg-sky-50',
  challenge_accepted: 'text-emerald-600 bg-emerald-50',
  challenge_declined: 'text-rose-600 bg-rose-50',
  match_accepted: 'text-green-600 bg-green-50',
  match_invitation: 'text-sky-600 bg-sky-50',
  match_started: 'text-sky-600 bg-sky-50',
  match_finished: 'text-sky-600 bg-sky-50',
  goal_scored: 'text-amber-600 bg-amber-50',
  live_match_started: 'text-amber-600 bg-amber-50',
  score_submitted: 'text-amber-600 bg-amber-50',
  score_confirmed: 'text-emerald-600 bg-emerald-50',
  score_disputed: 'text-rose-600 bg-rose-50',
  new_booking_request: 'text-orange-600 bg-orange-50',
  booking_confirmation: 'text-emerald-600 bg-emerald-50',
  booking_cancellation: 'text-rose-600 bg-rose-50',
  booking_rejected: 'text-rose-600 bg-rose-50',
  booking_completed: 'text-emerald-600 bg-emerald-50',
  reservation_approved: 'text-emerald-600 bg-emerald-50',
  reservation_rejected: 'text-rose-600 bg-rose-50',
  cancellation_requested: 'text-orange-600 bg-orange-50',
  cancellation_approved: 'text-emerald-600 bg-emerald-50',
  cancellation_rejected: 'text-rose-600 bg-rose-50',
  player_application_received: 'text-violet-600 bg-violet-50',
  player_application_accepted: 'text-emerald-600 bg-emerald-50',
  player_application_declined: 'text-rose-600 bg-rose-50',
  player_invite_received: 'text-violet-600 bg-violet-50',
  player_invite_accepted: 'text-emerald-600 bg-emerald-50',
  team_formation_request: 'text-green-600 bg-green-50',
  announcement: 'text-amber-600 bg-amber-50',
  new_follower: 'text-rose-600 bg-rose-50',
  new_comment: 'text-sky-600 bg-sky-50',
  comment_reply: 'text-sky-600 bg-sky-50',
  like: 'text-rose-600 bg-rose-50',
  player_review: 'text-amber-600 bg-amber-50',
  stadium_review: 'text-amber-600 bg-amber-50',
  player_awarded_mvp: 'text-amber-600 bg-amber-50',
  report: 'text-slate-500 bg-slate-100',
  system: 'text-slate-500 bg-slate-100',
}

export function iconFor(type, category) {
  return typeIcons[type] || categoryMeta[category]?.icon || Bell
}

export function colorFor(type, category) {
  return typeColors[type] || categoryMeta[category]?.cls || 'text-slate-500 bg-slate-100'
}
