# nixpacks.toml

providers = ["php" ]

[phases.setup]
nixPkgs = [
  "php",
  "phpPackages.composer",
  "nodejs",
  "libpng",
  "libjpeg",
  "freetype",
  "libzip",
  "libxml2",
  "curl",
  "libsodium",
  "oniguruma"
]
phpExtensions = [
  "gd",
  "pdo_mysql",
  "mbstring",
  "xml",
  "bcmath",
  "zip",
  "opcache",
  "sodium",
  "intl",
  "curl",
  "exif"
]

[phases.build]
cmds = ["composer install --no-dev --no-interaction --optimize-autoloader"] 
